baseURL = "https://u8739516597-dotcom.github.io/"
languageCode = "en-us"
title = "VR Locomotion Blog"
theme = "PaperMod"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mainSections = ["posts"]
  defaultContentLanguage = "en"
  # PaperMod 推荐的 profileMode 写法
  [params.profileMode]
    enabled = false

[params.assets]
  disableFingerprinting = true