baseURL = "https://u8739516597-dotcom.github.io/"
languageCode = "en-us"
title = "VR Locomotion Blog"
theme = "PaperMod"
publishDir = "docs"

# allow HTML in Markdown (img width, etc.)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mainSections = ["posts"]
  defaultContentLanguage = "en"
  profileMode = { enabled = false }  # 修改部分，将 profileMode 作为字典形式

[params.assets]
  disableFingerprinting = true
